### ISSUE TITLE
Request for community channel

### ISSUE THREAD

**Issue by terremoth** [ps2dev/ps2dev#13]
I saw there was no channel, until now.  
I created a telegram channel, @ps2dev or https://t.me/ps2dev  

I think telegram is a better place than an IRC channel.  
Please, appear there @rickgaiser  @fjtrujy  and other people involved.   
Let's grow up a little more our community? 
Help each other, write some more tutorials (in the internet has just a few), get Playstation 2 development docs lost in the internet, coding etc?

Please, join there

**Comment by fjtrujy** [comment]
Hello guys,
There is already a huge community in discord.
https://discord.gg/WUec3g

You can join and ask over there your issues/concerns

**Comment by AKuHAK** [comment]
> Hello guys,
> There is already a huge community in discord.
> https://discord.gg/WUec3g
> 
> You can join and ask over there your issues/concerns

Maybe it will be useful to reference this community somewhere in Readme?

**Comment by terremoth** [comment]
There is a VERY HUGE LACK of tutorials and HOWTO's in the internet about how to develop even a simple "hello world" program/elf for PS2.  
We need to change that too.  
We also need Graphic/Programming Engines such as RenderWare for helping develop PS2 Homebrews. I saw someone created an open source reimplementation of renderware engine btw (https://github.com/aap/librw).

**Comment by pedroduarte0** [comment]
> There is already a huge community in discord.
> https://discord.gg/WUec3g

When I tried to access it, I see a 'Invite Invalid' page. 'Thus invite may be expired, or you might not have permissoin to join.'
Does one need to be logged in to Discord to be able to see it? I currently don't have any account there (not very keen to create it still but if that is really a good place for information I am willing to consider).

**Comment by terremoth** [comment]
@pedroduarte0  this link will never expires:  
https://discord.gg/Se9W2e7
