### ISSUE TITLE
libtool not listed as a required package

### ISSUE THREAD

**Issue by Myriachan** [ps2dev/ps2dev#21]
`libtool` is not listed as a requirement on the readme, but it is required.

```
./libtool: 757: ./libtool: Cannot fork
Makefile:900: recipe for target 'init.lo' failed
make[3]: *** [init.lo] Error 2
```

**Comment by AKuHAK** [comment]
It is the problem with the folder permissions. You should not install libtool as it is an internal program that is inside the Binutils repo. This error means that you somewhere called scripts from the root, and somewhere from a user.
The solution: `sudo rm -rf $PS2DEV`, remove ps2dev downloaded repo (it will also contains misconfigured permission in `build` folder).
Then follow [these instructions](https://github.com/ps2dev/ps2dev): 2nd and 3rd step.
Then download the `ps2dev` repo and run scripts NOT from the root, but from a user.

**Comment by fjtrujy** [comment]
Closing issue because the readme already indicates that you need to have proper folder permissions.

Thanks
