### ISSUE TITLE
Xcode 12 build

### ISSUE THREAD

**Issue by tellowkrinkle** [ps2dev/ps2dev#23]
It appears the main issue is the compiler defaulting to `-Werror,-Wimplicit-function-declaration`

Specifically, it breaks some configure scripts' feature detection like [this](https://github.com/ps2dev/binutils-gdb/blob/9cca5c1781d1a03b9b3b61a3e5270cdb9c69295e/intl/configure#L992-L1000)

Not sure where you want to handle it, as a number of builds have this issue, but I can confirm that running `CFLAGS=-Wno-implicit-function-declaration ./build-all.sh` works

**Comment by fjtrujy** [comment]
It is failing with the legacy `binutils`, so if your solution is right, you should put the flag here:

https://github.com/ps2dev/ps2toolchain-iop/blob/main/scripts/001-binutils.sh#L39

and here:

https://github.com/ps2dev/ps2toolchain-dvp/blob/main/scripts/001-binutils.sh#L39

Actually, if you take a look, we already have some custom flags for `Darwin`

**Comment by fjtrujy** [comment]
Hello @tellowkrinkle,

I have fixed the compilation using Xcode 12.

https://github.com/ps2dev/ps2toolchain-dvp/pull/4
https://github.com/ps2dev/ps2toolchain-iop/pull/4

Please, try again and close the issue if it is working for you. So far in the CI is already working as you can see here

https://github.com/ps2dev/ps2dev/pull/27

Thanks!
