### ISSUE TITLE
Release v1.2.0 - "ps2dev-ubuntu-latest" does not have ps2toolchain-gcc-10

### ISSUE THREAD

**Issue by mscofield0** [ps2dev/ps2dev#24]

**Comment by AKuHAK** [comment]
Please more info. If you are talking about Docker images, such image does not exist, please be more detailed.

**Comment by fjtrujy** [comment]
Please @mscofield0, explain better what you mean.
Thanks

**Comment by mscofield0** [comment]
Release v1.2.0 does not come with gcc-10.

Steps:

- Download the release, 
- Extract to `/usr/local/ps2dev/`, 
- Run `ee-g++ --version`
- Output is 3.2.3

**Comment by fjtrujy** [comment]
v1.20 doesn't include GCC 10.

Currently, the new toolchain is just available from the Master branch, but it wasn't tagged yet.
We need to perform more testing before do it.

So if you want to have the latest toolchain with GCC10 you need to go to actions
https://github.com/ps2dev/ps2dev/actions
Then enter in the latest `CI` workflow, and then from there, you can download `ubuntu` and `macos`. 
Anyway, my recommendation is to fully compile yourself.

Closing issue.
