### ISSUE TITLE
./build-all.sh finishes only if the ps2dev folder is in /usr/local/ps2dev

### ISSUE THREAD

**Issue by mscofield0** [ps2dev/ps2dev#25]
Can someone explain why?

**Comment by AKuHAK** [comment]
I changed ps2dev location and every script finishes normally.
However you have restrictions. You should have full access to directory. No spaces and non-latin characters in absoulte path. No realtive path, only paths that starts at `/`

**Comment by fjtrujy** [comment]
As the readme says:
```
Note: Ensure that you have full access to the PS2DEV path. You can change the PS2DEV path with the following requirements: use only absolute paths, don't use spaces, use only Latin characters.
```

Closing issue.
Thanks

**Comment by mscofield0** [comment]
I had ownership of the `/usr/local/ps2dev` folder and all its folders.
