### ISSUE TITLE
Building gsKit with libpng

### ISSUE THREAD

**Issue by Zach128** [ps2dev/ps2dev#28]
I'm interested in building gsKit with support for libpng from the sdk ports. From what I gathered, it should involve building changing the build order to this:

- ps2toolchain
- ps2sdk
- ps2sdk-ports
- gsKit
- everything else

Also, if I'm not mistaken, could we simply call the "setup.sh" script in gsKit for building it?

**Comment by fjtrujy** [comment]
This is not really true. 
There is a circular dependency, in your do in your way you can't compile SDL.

If we want to fix this circular dependency additional changes must be done.

**Comment by Zach128** [comment]
True, was struggling with that realisation the other day. Is there anything I could possibly do to help resolve it?

**Comment by fjtrujy** [comment]
The current way is :
- ps2toolchain
- ps2sdk
- gsKit
- ps2sdk-ports
- gsKit (again, this time using if you want the `setup.sh`)

**Comment by fjtrujy** [comment]
you just can navigate to `build/gskit` and from there execute `./setup.sh` after the normal installation finished.

**Comment by Zach128** [comment]
Okay, thanks for the help. Think I can close the issue in that case.
