### ISSUE TITLE
Add "cmake" as requirement.

### ISSUE THREAD

**Issue by dirsors** [ps2dev/ps2dev#34]
I would like to suggest "cmake" as a requirement because the script also compiles and installs ps2sdk-ports. And add "ps2sdk-ports" to the "These scripts download (git clone) and install" list.
Without cmake, the build-all.sh returns "cmake: command not found."

**Comment by fjtrujy** [comment]
So, please let's create a PR.
Thanks

**Comment by terremoth** [comment]
I created a PR #39 for it.

**Comment by fjtrujy** [comment]
Closing because it was added with #39
