### ISSUE TITLE
libpng doesn't work after update

### ISSUE THREAD

**Issue by h4570** [ps2dev/ps2dev#37]
Hi.

After ps2dev update it turned that libpng doesnt work in my project. 
To be 100% sure that is not my fault, I tried to reproduce this bug in gsKit and problem is also there.
I was wondering where to put this PR, but I think the problem is more with the toolchain than with libpng or gsKit itself.

## Which line cause the problem:
```
FILE *file = fopen("host:files/test.png", "rb");
png_structp png_ptr = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL); // <-- Problem is here
png_infop info_ptr = png_create_info_struct(png_ptr);
...
```

## Repro steps:
1. `GSKITSRC=cloned-ps2dev/build/gskit`
2. `cd $GSKITSRC`
3. Uncomment `LIBPNG` and `ZLIB` in `Makefile.pref`
4. `make`
5. Open `./examples/png-texture/textures.elf` in PCSX2
6. ![image](https://user-images.githubusercontent.com/32263891/119804814-fce8d080-bee0-11eb-91f6-9c719e121156.png)

## Code snippet:
```
#include <png.h>

// CFlags: -DHAVE_LIBPNG -DHAVE_ZLIB
// LDFlags: -L$(PS2SDK)/ports/lib
// EELibs: -lpng -lz

FILE *file = fopen("host:files/test.png", "rb");
assertMsg(file != NULL, "Failed to open .png file!");
unsigned char header[8];
fread(header, 1, 8, file);
assertMsg(!png_sig_cmp(header, 0, 8), "File was not recognized as a PNG file");
png_structp png_ptr = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
assertMsg(png_ptr, "PNG read struct init failed!");
png_infop info_ptr = png_create_info_struct(png_ptr);
assertMsg(info_ptr, "PNG info struct init failed!");
assertMsg(!setjmp(png_jmpbuf(png_ptr)), "PNG reader fatal error!");
png_read_end(png_ptr, NULL);
png_destroy_read_struct(&png_ptr, &info_ptr, (png_infopp)NULL);
fclose(file);
```

Thanks

**Comment by fjtrujy** [comment]
Hello
I think you're wrong, there is a cyclic dependency between `gskit` a `ps2sdk-ports`
If you want to have `gskit` with png support, you need:
- To compile first `gskit` without png-support
- Then `ps2sdk-ports` (which compiles `libpng`) 
- Finally you need to compile again `gskit` enabling the png support

Actually to demonstrate that you're wrong
You can download artifacts from gsKit
https://github.com/ps2dev/gsKit/actions/runs/854668541

Here you have it, running locally:
<img width="1350" alt="Screenshot 2021-05-27 at 12 30 26" src="https://user-images.githubusercontent.com/10010409/119813535-b3e94a00-bee9-11eb-80f5-050d0386c8bc.png">


Quite important note: I saw you're using `PCSX2`, for this example is fine, but `host` unit doesn't contain all the I/O functions implemented in `PCSX2`, as `readdir`, `stat`.... so I have done a PR which is waiting to be merged
https://github.com/PCSX2/pcsx2/pull/4372

Please, test it and close the issue.
Thanks

**Comment by fjtrujy** [comment]
By the way, the same issue was already replied
https://github.com/ps2dev/ps2dev/issues/28

**Comment by h4570** [comment]
Worked. Thanks man!
