### ISSUE TITLE
Script fails; make[3]: mipsel-ps2-irx-gcc: Command not found

### ISSUE THREAD

**Issue by martravi** [ps2dev/ps2dev#41]
Tried it on Ubuntu 20.04 LTS on a physical machine as well as on WSL2; both ended up with the same problem:

make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[3]: mipsel-ps2-irx-gcc: Command not found
make[2]: mipsel-ps2-irx-gcc: Command not found
Nothing to clean in samples
make[2]: mipsel-ps2-irx-gcc: Command not found
make[2]: mipsel-ps2-irx-ar: Command not found
make[2]: *** [/usr/local/ps2dev/ps2dev/build/ps2sdk/iop/Rules.make:109: lib/libkernel.a] Error 127
make[1]: *** [/usr/local/ps2dev/ps2dev/build/ps2sdk/Rules.make:21: all-kernel] Error 2
make: *** [Makefile:31: all-iop] Error 2
../scripts/002-ps2sdk.sh: Failed.

**Comment by AKuHAK** [comment]
@fjtrujy the same error is presented also in the github actions:
https://github.com/ps2dev/ps2dev/runs/2892922865?check_suite_focus=true#step:6:7010

**Comment by fjtrujy** [comment]
It means that GCC for IOP is failing to compile using `WSL` or `Windows`

**Comment by fjtrujy** [comment]
However here:
https://github.com/ps2dev/ps2toolchain-iop/runs/2892692682?check_suite_focus=true

Prints versions works:
```
Run export PS2DEV=$PWD/ps2dev
GNU assembler (GNU Binutils) 2.35.2
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `mipsel-ps2-irx'.
GNU ld (GNU Binutils) 2.35.2
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
mipsel-ps2-irx-gcc.exe (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Maybe is something about missing variable in the path?

**Comment by AKuHAK** [comment]
> It means that GCC for IOP is failing to compile using `WSL` or `Windows`

Mac os fail as well

**Comment by fjtrujy** [comment]
@martravi can you put the logs of the `ps2toolchain-iop` compilation.

Anyway, after further investigation, I think this is happening to you because you are not doing a clean installation.
Can you just try to remove your `$PS2DEV` folder and try again?
Also, remove the `build` folder inside of the `ps2dev` repo, which is where we save temp files.

Thanks

**Comment by AKuHAK** [comment]
Now this is mentioned in the readme (step 2), so probably can be closed

**Comment by fjtrujy** [comment]
Yes, closing issue.
Thanks!
