### ISSUE TITLE
Several components' configure scripts are outdated

### ISSUE THREAD

**Issue by ticky** [ps2dev/ps2dev#43]
The `config.guess` and related `configure` scripts within the following modules are quite old, which prevents building on younger platforms like aarch64 MacOS (added to autoconf's source tree in [mid 2020](https://git.savannah.gnu.org/gitweb/?p=config.git;a=commit;h=2593751ef276497e312d7c4ce7fd049614c7bf80)), it'd be great if they could be `autoreconf`'ed (either within the repositories, or as part of the dependency building scripts) to allow for this!

I've attempted to enumerate the troublesome dependencies, but it's quite possible I've missed some:

- https://github.com/ps2dev/binutils-gdb/blob/dvp-v2.14/config.guess#L6 (circa 2003!)
- https://github.com/ps2dev/binutils-gdb/blob/iop-v2.35.2/config.guess#L5 (early 2020)
- https://github.com/ps2dev/newlib/blob/ee-v4.1.0/config.guess#L5 (2019)

Due to the way the toolchain is bootstrapped, this is pretty difficult to easily patch around, so I hope you can help :)

**Comment by tmcintos** [comment]
Yes, in my experience, building on macOS for Apple Silicon Mac fails; would be great if it worked.

**Comment by fjtrujy** [comment]
Scripts were updated, and compilation for MacOS Apple Silicon is now possible.
Please reopen it if you are still suffering issues
