### ISSUE TITLE
Confusion over compiler binaries and naming...

### ISSUE THREAD

**Issue by Arawn-Davies** [ps2dev/ps2dev#44]
Forgive me in case I've missed something out, but I've just compiled and I can't find any binaries in my path with the usual names of ee-gcc, iop-gcc etc., I've got ```mips64r5900el-ps2-elf-gcc``` and other compilers/linkers/etc. installed, but these are also targeting new GCC versions (11.1.0).

Are there any major differences I need to add in order to target these compilers from old source Makefiles, or is it done seamlessly? 
Thanks for keeping the PS2 toolchain alive :)

**Comment by fjtrujy** [comment]
Hello, previously `ee-gcc` and `iop-gcc` it wasn't following proper naming conventions, now `mips64r5900el-ps2-elf-gcc` is the equivalent of EE and `mipsel-ps2-irx-gcc` is the equivalent for IOP

You can take a look here

https://github.com/ps2dev/ps2sdk/blob/master/samples/Makefile.pref_sample

**Comment by AKuHAK** [comment]
@Arawn-Davies and anyway in the old toolchain it was not proper to directly call GCC compiler name directly. Instead of calling `ee-gcc` you always should call `$(EE_CC)`, this will work always.
