### ISSUE TITLE
Compiler segfaults during configure

### ISSUE THREAD

**Issue by DarjanKrijan** [ps2dev/ps2dev#49]
I keep getting weird compiler segfaults during ps2toolchain-dvp `configure` that I've not seen ever before:
[build-all_log.txt](https://github.com/ps2dev/ps2dev/files/8311824/build-all_log.txt)

I'm on an updated Arch Linux with GCC 11.2.0.

Rebuilding binutils/gdb for x86_64 runs through fine here.

Any ideas?

EDIT:
A month ago this ran through w/o many problems (apart from finding python stuff, that's now gone).

**Comment by DarjanKrijan** [comment]
I can work with the[ latest dev build](https://github.com/ps2dev/ps2dev/releases/download/latest/ps2dev-ubuntu-latest.tar.gz) for now.

**Comment by uyjulian** [comment]
Probably issues with gcc in arch linux.

This doesn't seem to be an issue anymore. Reopen if this is not the case
