### ISSUE TITLE
can't execute binaries in macOS Catalina (10.15.4)

### ISSUE THREAD

**Issue by bucanero** [ps2dev/ps2dev#5]
Most probably due to macOS security checks, after unpacking the ps2dev macOS `.tar.gz`, trying to execute any binary brings up an error. For example:

`"ps2client" cannot be opened because the developer cannot be verified.`

<img width="423" alt="Screenshot 2020-05-22 14 37 08" src="https://user-images.githubusercontent.com/1153055/82694525-c3301a80-9c39-11ea-9af3-5eb8d84fe754.png">

Perhaps an explanation on how to disable the quarantine status for the `ps2dev` folder in macOS could be added to the Readme.

**Comment by fjtrujy** [comment]
I will try in Catalina next week, 
I have tried to use the precompiled one in Mojave and worked without any issue.
Mainwhile you can try this works around

```
Apparently, the workaround is quite painful:

In the Finder on your Mac, locate the app you want to open.
Control-click the app icon, then choose Open from the shortcut menu.
Click Open.
The app is saved as an exception to your security settings, and you can open it in the future by double-clicking it or from cli, just as you can with any authorised app.
```

**Comment by Velocet** [comment]
I'm on Catalina (10.15.5) and use these settings to get rid of this behaviour:
Disable Gatekeeper:
`sudo spctl --master-disable`
`sudo defaults write com.apple.LaunchServices LSQuarantine -bool NO`

Enable _Allow from anywhere_ in the security preferences pane (not working on 10.15.x):
`sudo defaults write com.apple.security GKAutoRearm -bool NO`

Remove quarantine attribute recursively for ps2dev (_developer cannot be verified_):
`xattr -dr com.apple.quarantine "$HOME/Downloads/ps2dev" `

Add the terminal as a developer tool:
`spctl developer-mode enable-terminal`

I also did the following "tweaks" to my Catalina installation:
- Disable System Integrity Protection (SIP)
  - Boot into recovery: ⌘ + R while booting
  - Utilities > Terminal: `csrutil disable` 
- Fully disable SIP: `sudo nvram csr-active-config='%ff%00%00%00'`
- boot-args:
  - Disable Apple Mobile File Integrity (AMFI): amfi_get_out_of_my_way=1
  - Allow any digital signature: amfi_allow_any_signature=1
  - Disable code signing enforcement: cs_enforcement_disable=1

**Comment by bucanero** [comment]
thanks @Velocet for the info and details 👍 
in my case, I feel it's a bit overkill to require disabling so many security checks to run the binary build.

In this situation I'd probably build the ps2 toolchain locally from scratch, so I can execute it while keeping the security.

On a related note, I wonder how the [PSVita SDK](https://github.com/vitasdk/autobuilds) is creating the binary builds, because I installed them and I didn't get any security error on macOS Catalina.

**Comment by Velocet** [comment]
Seems you already changed your settings without knowing when installing Xcode. This normally executes `spctl developer-mode enable-terminal`. This could be the reason you didn't get any warning when using the PSVita SDK via terminal.

You don't have to manually build the toolchain from scratch. Just run this on the extracted files:
`xattr -dr com.apple.quarantine "path/to/ps2toolchain"`

**Comment by bucanero** [comment]
just to confirm, running
```bash
xattr -dr com.apple.quarantine path/to/ps2toolchain
```
fixed the issue on macOS Catalina.

Adding a note on the `Readme` about these security settings could be useful for other users.

**Comment by Velocet** [comment]
You are free to make a PR ;)

**Comment by bucanero** [comment]
Note added in #7
