### ISSUE TITLE
Will Not Compile

### ISSUE THREAD

**Issue by godreborn** [ps2dev/ps2dev#62]
I get this error:

CMake Error at CMakeLists.txt:402 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "DEPRECATION" is not allowed.

-- Configuring incomplete, errors occurred!
See also "/home/godreborn/ps2dev/build/ps2sdk-ports/build/SDL_ttf/build/CMakeFiles/CMakeOutput.log".
See also "/home/godreborn/ps2dev/build/ps2sdk-ports/build/SDL_ttf/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:27: cmakelibs] Error 1
../scripts/004-ps2sdk-ports.sh: Failed.

**Comment by uyjulian** [comment]
Possible outdated cmake version.

This doesn't seem to be an issue anymore. Reopen if this is not the case
