### ISSUE TITLE
Continued failing Windows builds

### ISSUE THREAD

**Issue by StarWolf3000** [ps2dev/ps2dev#64]
The following build from GH Actions was successful for Ubuntu and macos, but not Windows with msys2:
[actions/runs/3670801519/jobs/6205575662](https://github.com/ps2dev/ps2dev/actions/runs/3670801519/jobs/6205575662)

Step 6 (Run all stages in the shell) exited with error code 1 (see line 3864 in log), due to an error from configure:
```
configure: error: Building GCC requires GMP 4.2+, MPFR 3.1.0+ and MPC 0.8.0+.
Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify
their locations.  Source code for these libraries can be found at
their respective hosting sites as well as at
[https://gcc.gnu.org/pub/gcc/infrastructure/.](https://gcc.gnu.org/pub/gcc/infrastructure/)  See also
http://gcc.gnu.org/install/prerequisites.html for additional info.  If
you obtained GMP, MPFR and/or MPC from a vendor distribution package,
make sure that you have installed both the libraries and the header
files.  They may be located in separate packages.
../scripts/002-gcc-stage1.sh: Failed.
../scripts/002-iop.sh: Failed.
../scripts/001-toolchain.sh: Failed.
Error: Process completed with exit code 1.
```

The build did not stop, but instead uploaded incomplete artifacts for Windows (just 18 MB instead of about 150 MB).

**Comment by StarWolf3000** [comment]
Fixed via [actions/runs/3767106879/jobs/6404316756](https://github.com/ps2dev/ps2dev/actions/runs/3767106879/jobs/6404316756)

**Comment by StarWolf3000** [comment]
Another job for Windows was unsuccessful, this time there was an error with the GCC source: [actions/runs/3897833095/jobs/6655915877](https://github.com/ps2dev/ps2dev/actions/runs/3897833095/jobs/6655915877)
![Screenshot_20230113-083034](https://user-images.githubusercontent.com/787808/212263052-2a5c8f91-183b-45e6-943d-32dbd028e2a6.png)

**Comment by StarWolf3000** [comment]
Since its been failing for about two weeks now, because of an issue with the GCC source, is there a patch required for the latest source, so it compiles again on msys2/mingw?

**Comment by AKuHAK** [comment]
fixed in https://github.com/ps2dev/ps2toolchain-ee/pull/28
