### ISSUE TITLE
Building fails in Ubuntu 18.04.6 with arch x86

### ISSUE THREAD

**Issue by cdlt** [ps2dev/ps2dev#74]
Problems using:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
Architecture: x86
Kernel: 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:16:44 UTC 2018 i686 athlon i686 GNU/Linux

./build-all.sh
Without errors in 001-toolchain.sh

Errors in 002-toolchain.sh:

Installing latest environment status
Using repo reference origin/master
HEAD está ahora en 6b656d1a Merge pull request #461 from crypt4489/MIPTBP_fixes
Nothing to clean in samples
Cleaning PS2SDK dependencies.
Cleaning lwip.
src/ps2-irxgen.c: In function ‘load_file’:
src/ps2-irxgen.c:145:4: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    (void) fread(data, 1, size, fp);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ff.c:3282:13: warning: 'find_volume' defined but not used [-Wunused-function]
 3282 | static UINT find_volume (       /* Returns BS status found in the hosting drive */
      |             ^~~~~~~~~~~
obj/ioplib.o: in function `ioplib_getByName':
(.text+0xc): jump to a non-instruction-aligned address
collect2: error: ld returned 1 exit status
/home/cdlt/SDKs/ps2dev/build/ps2sdk/iop/Rules.make:120: fallo en las instrucciones para el objetivo 'irx/mx4sio_bd.irx'
make[3]: *** [irx/mx4sio_bd.irx] Error 1
/home/cdlt/SDKs/ps2dev/build/ps2sdk/Rules.make:21: fallo en las instrucciones para el objetivo 'all-mx4sio_bd'
make[2]: *** [all-mx4sio_bd] Error 2
/home/cdlt/SDKs/ps2dev/build/ps2sdk/Rules.make:21: fallo en las instrucciones para el objetivo 'all-sio'
make[1]: *** [all-sio] Error 2
Makefile:33: fallo en las instrucciones para el objetivo 'all-iop'
make: *** [all-iop] Error 2
../scripts/002-ps2sdk.sh: Failed.

**Comment by uyjulian** [comment]
This doesn't seem to be an issue anymore. Reopen if this is not the case
