### ISSUE TITLE
Makefile:29: S2DEV/ps2sdk/Defs.make: No existe el fichero o el directorio

### ISSUE THREAD

**Issue by TioComeGfas** [ps2dev/ps2dev#8]
SO: Debian 10 buster x64

Hello, I have a problem when I run ./build-all.sh
I have the variables $PS2DEV, $PS2SDK and $GSKIT according to the readme.md of the repository

`tiocomegfas@debian-msi:/usr/local$ echo $PS2DEV`
`/usr/local/ps2dev`
`tiocomegfas@debian-msi:/usr/local$ echo $PS2SDK`
`$PS2DEV/ps2sdk`
`tiocomegfas@debian-msi:/usr/local$ echo $GSKIT`
`$PS2DEV/gsKit`

ran the bash and it gives me this error:

`Clonando en 'gsKit'...`
`remote: Enumerating objects: 29, done.`
`remote: Counting objects: 100% (29/29), done.`
`remote: Compressing objects: 100% (24/24), done.`
`remote: Total 2552 (delta 8), reused 3 (delta 1), pack-reused 2523`
`Recibiendo objetos: 100% (2552/2552), 4.09 MiB | 335.00 KiB/s, listo.`
`Resolviendo deltas: 100% (1702/1702), listo.`
`Makefile:29: S2DEV/ps2sdk/Defs.make: No existe el fichero o el directorio`
`make: *** No hay ninguna regla para construir el objetivo 'S2DEV/ps2sdk/Defs.make'.  Alto.`
`../scripts/003-gskit.sh: Failed.`

Thank you and I remain attentive to your comments

**Comment by rickgaiser** [comment]
> tiocomegfas@debian-msi:/usr/local$ echo $PS2DEV
> /usr/local/ps2dev
> tiocomegfas@debian-msi:/usr/local$ echo $PS2SDK
> $PS2DEV/ps2sdk
> tiocomegfas@debian-msi:/usr/local$ echo $GSKIT
> $PS2DEV/gsKit

$PS2DEV/ps2sdk should be /usr/local/ps2dev/ps2sdk
$PS2DEV/gsKit should be /usr/local/ps2dev/gsKit

As a result this:
'S2DEV/ps2sdk/Defs.make' should be '/usr/local/ps2dev/ps2sdk/Defs.make'

**Comment by TioComeGfas** [comment]
perfect! now it worked perfectly, thanks !!
