### ISSUE TITLE
PROBLEM: Issues building

### ISSUE THREAD

**Issue by wolfmanvid01** [ps2dev/ps2dev#86]
when trying to compile older projects something like this appears, most often than not

src/supportbase.c:360:38: error: 'struct dirent' has no member named 'd_stat'
  360 |                 game->sizeMB = dirent->d_stat.st_size >> 20;

and i cannot find a ps2dev binary that works thats below gcc14. And the ones i find say something like "mips64r5900el-ps2-elf-gcc No such file or directory" even when the binary exists and i have the environment variables well set. 

Im new on this and frustrated asf

**Comment by wolfmanvid01** [comment]
And if i go to this repo, there arent ps2dev versions other than the latest one

**Comment by fjtrujy** [comment]
During the latest years we have done tons of improvements on the toolchain. This obviously brings several breaking changes like the one you are facing.
My main recommendation is to update your legacy project.
`dirent->d_stat.st_size` wasn't following the POSIX standards this is why it was deleted.
If you want to retrieve the size of the file most probably you will require to do a `stat` call.

You can post here your code if you have issues migrating to new standards.

Cheers.
